name = "stm32_hal"
description = "stm32 : devices, drivers, svd"
version = "0.1.0"

authors = ["AdaCore"]
maintainers = ["Olivier Henley <olivier.henley@gmail.com>"]
maintainers-logins = ["ohenley"]
website="https://github.com/GNAT-Academic-Program/stm32_hal"
tags = ["embedded", "stm32", "devices", "drivers", "svd"]

[[depends-on]]
cortex_m = "0.5.0"
hal = "~0.3.0"

[configuration.variables]
device = { type = "Enum", values = ["stm32f746", "stm32f429"], default = "stm32f429" }

#[configuration.values]
#cortex_m.core = "m4f"